name: azure/resource-group/create
schema: |
  {
    "properties": {
      "id": { "type": "string" },
      "type": { "type": "string" },
      "name": { "type": "string" },
      "location": { "type": "string" }
    },
    "optionalProperties": {
      "description": { "type": "string" }
    }
  }
script:
  run: |
    az group create 
      --location "${evaluate(data.location)}"
      --name "${evaluate(data.name)}"
      --only-show-errors
  rollback: |
    az group delete 
      --name "${evaluate(data.name})"
      --only-show-errors
      --yes
