name: azure/resource-group/delete
schema: |
  {
    "properties": {
      "id": { "type": "string" },
      "type": { "type": "string" },
      "name": { "type": "string" }
    },
    "optionalProperties": {
      "description": { "type": "string" },
      "location": { "type": "string" },
      "no-wait": { "type": "boolean" }
    }
  }
script:
  type: js
  preamble: |
    const name = await evaluate(data.name);
  run: |
    const noWait = data['no-wait'] === undefined ? false : await evaluate(data['no-wait']) ?? false;
    
    await az(`group delete 
      --name "${name}"
      --only-show-errors
      --yes
      ${noWait ? "--no-wait" : ""}`);
  rollback: |
    const location = await evaluate(data.location);

    if (location === undefined || location === "")
      throw Error(".location is empty");

    await az(`group create 
      --name "${name}"
      --location "${location}"
      --only-show-errors`);
