// Code generated by jtd-codegen for TypeScript v0.2.1

export interface HandlerSchemaRun {
  script: string;
}

export interface HandlerSchemaRollback {
  script: string;
}

export interface HandlerSchema {
  name: string;
  run: HandlerSchemaRun;
  schema: string;
  rollback?: HandlerSchemaRollback;
}
