- id: create-store-resource-group
  hash: dbec01b271f9d0924d93fa096ad92cb4a842c311ee3771d1831392cd7b8f2d6d
  when: 2022-06-18T12:53:34.716Z
  output:
    - |-
      {
        "id": "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSS",
        "location": "centralus",
        "managedBy": null,
        "name": "tutorialAzureFuncCosmosCSS",
        "properties": {
          "provisioningState": "Succeeded"
        },
        "tags": null,
        "type": "Microsoft.Resources/resourceGroups"
      }
- id: create-compute-resource-group
  hash: 8bba999c381e675e7fcce5412e9d3a73f440f9925ab5af59bb264ed1be4156ee
  when: 2022-06-18T12:53:36.132Z
  output:
    - |-
      {
        "id": "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSC",
        "location": "centralus",
        "managedBy": null,
        "name": "tutorialAzureFuncCosmosCSC",
        "properties": {
          "provisioningState": "Succeeded"
        },
        "tags": null,
        "type": "Microsoft.Resources/resourceGroups"
      }
- id: create-cosmos-db
  hash: e9133d84d042f729bb9e097428d401275979981d80218ac06bd4ba5928735933
  when: 2022-06-18T12:56:48.197Z
  output:
    - |-
      {
        "analyticalStorageConfiguration": {
          "schemaType": "WellDefined"
        },
        "apiProperties": null,
        "backupPolicy": {
          "migrationState": null,
          "periodicModeProperties": {
            "backupIntervalInMinutes": 240,
            "backupRetentionIntervalInHours": 8,
            "backupStorageRedundancy": "Geo"
          },
          "type": "Periodic"
        },
        "capabilities": [],
        "capacity": null,
        "connectorOffer": null,
        "consistencyPolicy": {
          "defaultConsistencyLevel": "Session",
          "maxIntervalInSeconds": 5,
          "maxStalenessPrefix": 100
        },
        "cors": [],
        "createMode": null,
        "databaseAccountOfferType": "Standard",
        "defaultIdentity": "FirstPartyIdentity",
        "disableKeyBasedMetadataWriteAccess": false,
        "disableLocalAuth": false,
        "documentEndpoint": "https://tafccdb.documents.azure.com:443/",
        "enableAnalyticalStorage": false,
        "enableAutomaticFailover": false,
        "enableCassandraConnector": null,
        "enableFreeTier": false,
        "enableMultipleWriteLocations": false,
        "failoverPolicies": [
          {
            "failoverPriority": 0,
            "id": "tafccdb-westus",
            "locationName": "West US"
          }
        ],
        "id": "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSS/providers/Microsoft.DocumentDB/databaseAccounts/tafccdb",
        "identity": {
          "principalId": null,
          "tenantId": null,
          "type": "None",
          "userAssignedIdentities": null
        },
        "instanceId": "38c45591-f2d9-43d5-a5c4-217da4c234b0",
        "ipRules": [],
        "isVirtualNetworkFilterEnabled": false,
        "keyVaultKeyUri": null,
        "kind": "GlobalDocumentDB",
        "location": "Central US",
        "locations": [
          {
            "documentEndpoint": "https://tafccdb-westus.documents.azure.com:443/",
            "failoverPriority": 0,
            "id": "tafccdb-westus",
            "isZoneRedundant": false,
            "locationName": "West US",
            "provisioningState": "Succeeded"
          }
        ],
        "name": "tafccdb",
        "networkAclBypass": "None",
        "networkAclBypassResourceIds": [],
        "privateEndpointConnections": null,
        "provisioningState": "Succeeded",
        "publicNetworkAccess": "Enabled",
        "readLocations": [
          {
            "documentEndpoint": "https://tafccdb-westus.documents.azure.com:443/",
            "failoverPriority": 0,
            "id": "tafccdb-westus",
            "isZoneRedundant": false,
            "locationName": "West US",
            "provisioningState": "Succeeded"
          }
        ],
        "resourceGroup": "tutorialAzureFuncCosmosCSS",
        "restoreParameters": null,
        "systemData": {
          "createdAt": "2022-06-18T12:55:08.575071+00:00",
          "createdBy": null,
          "createdByType": null,
          "lastModifiedAt": null,
          "lastModifiedBy": null,
          "lastModifiedByType": null
        },
        "tags": {},
        "type": "Microsoft.DocumentDB/databaseAccounts",
        "virtualNetworkRules": [],
        "writeLocations": [
          {
            "documentEndpoint": "https://tafccdb-westus.documents.azure.com:443/",
            "failoverPriority": 0,
            "id": "tafccdb-westus",
            "isZoneRedundant": false,
            "locationName": "West US",
            "provisioningState": "Succeeded"
          }
        ]
      }
    - |-
      {
        "id": "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSS/providers/Microsoft.DocumentDB/databaseAccounts/tafccdb/sqlDatabases/FriendDatabase",
        "location": null,
        "name": "FriendDatabase",
        "options": null,
        "resource": {
          "_self": "dbs/qdBRAA==/",
          "colls": "colls/",
          "etag": "\"0000d204-0000-0700-0000-62adcb580000\"",
          "id": "FriendDatabase",
          "rid": "qdBRAA==",
          "ts": 1655556952.0,
          "users": "users/"
        },
        "resourceGroup": "tutorialAzureFuncCosmosCSS",
        "tags": null,
        "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases"
      }
    - |-
      {
        "id": "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSS/providers/Microsoft.DocumentDB/databaseAccounts/tafccdb/sqlDatabases/FriendDatabase/containers/FriendContainer",
        "location": null,
        "name": "FriendContainer",
        "options": null,
        "resource": {
          "_conflicts": "conflicts/",
          "_docs": "docs/",
          "_self": "dbs/qdBRAA==/colls/qdBRAPumFzk=/",
          "_sprocs": "sprocs/",
          "_triggers": "triggers/",
          "_udfs": "udfs/",
          "analyticalStorageTtl": null,
          "conflictResolutionPolicy": {
            "conflictResolutionPath": "/_ts",
            "conflictResolutionProcedure": "",
            "mode": "LastWriterWins"
          },
          "defaultTtl": null,
          "etag": "\"0000d404-0000-0700-0000-62adcb760000\"",
          "geospatialConfig": {
            "type": "Geography"
          },
          "id": "FriendContainer",
          "indexingPolicy": {
            "automatic": true,
            "compositeIndexes": null,
            "excludedPaths": [
              {
                "path": "/\"_etag\"/?"
              }
            ],
            "includedPaths": [
              {
                "indexes": null,
                "path": "/*"
              }
            ],
            "indexingMode": "consistent",
            "spatialIndexes": null
          },
          "partitionKey": {
            "kind": "Hash",
            "paths": [
              "/LastName"
            ],
            "systemKey": null,
            "version": null
          },
          "rid": "qdBRAPumFzk=",
          "statistics": [
            {
              "documentCount": 0,
              "id": "0",
              "partitionKeys": [],
              "sampledDistinctPartitionKeyCount": 0,
              "sizeInKB": 0
            }
          ],
          "ts": 1655556982.0,
          "uniqueKeyPolicy": {
            "uniqueKeys": []
          }
        },
        "resourceGroup": "tutorialAzureFuncCosmosCSS",
        "tags": null,
        "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers"
      }
- id: create-cosmos-cli-role
  hash: 7c950f8bbc0db6e795ff579c2049b4b4b23d5baab30873deb87f49132e19b53c
  when: 2022-06-18T12:57:19.976Z
  output:
    - |-
      {
        "assignableScopes": [
          "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSS/providers/Microsoft.DocumentDB/databaseAccounts/tafccdb"
        ],
        "id": "/subscriptions/2ee96cab-57d3-472f-9d74-b9a9dc556def/resourceGroups/tutorialAzureFuncCosmosCSS/providers/Microsoft.DocumentDB/databaseAccounts/tafccdb/sqlRoleDefinitions/ef7a55a8-2186-4f0a-9033-c837c1b96b13",
        "name": "ef7a55a8-2186-4f0a-9033-c837c1b96b13",
        "permissions": [
          {
            "dataActions": [
              "Microsoft.DocumentDB/databaseAccounts/readMetadata",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/*",
              "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/*"
            ],
            "notDataActions": []
          }
        ],
        "resourceGroup": "tutorialAzureFuncCosmosCSS",
        "roleName": "CLIRole",
        "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions",
        "typePropertiesType": "CustomRole"
      }
