preamble: |
  env("StoreRG", "tutorialAzureFuncCosmosCSS");
  env("ComputeRG", "tutorialAzureFuncCosmosCSC");
  env("AccountName", "tafccdb");

actions:
  - id: create-store-resource-group
    type: azure/resource-group/create
    name: ${StoreRG}
    location: centralus
    no-wait: true

  - id: create-compute-resource-group
    type: azure/resource-group/create
    name: ${ComputeRG}
    location: centralus
    no-wait: true

  - id: create-cosmos-db
    type: azure/cosmos/create
    resource-group: ${StoreRG}
    account-name: ${AccountName}
    location: westus
    databases:
      - name: FriendDatabase
        containers:
          - name: FriendContainer
            partition-key-path: /LastName
  
  - id: create-cosmos-cli-role
    type: azure/cosmos/create-role
    resource-group: ${StoreRG}
    account-name: ${AccountName}
    role-name: CLIRole
    body: "@CLIRole.json"

  - id: assign-cli-role-to-principal
    type: azure/cosmos/create-assignment
    resource-group: ${StoreRG}
    account-name: ${AccountName}
    principal-id: 22395703-af19-49be-a81f-ba230562fce3
    role-name: "CLIRole"

  - id: populate-cosmos-db
    type: azure/cli/az
    run: |
      ../../scripts/build-database-content.sh


