actions:
  - id: 001-create-RG
    type: azure/resource-group/create
    name: ${env('RESOURCE_GROUP_NAME')}
    location: centralus

  - id: 002-create-DB
    type: azure/cosmos/create
    resource-group: ${env('RESOURCE_GROUP_NAME')}
    account-name: ${env('COSMOS_ACCOUNT_NAME')}
    location: westus
    databases:
      - name: FriendDatabase
        containers:
          - name: FriendContainer
            partition-key-path: /LastName
