preamble: |
  env("ResourceGroup", env('RESOURCE_GROUP_NAME'));
  env("AccountName", env('COSMOS_ACCOUNT_NAME'));

actions:
  - id: create-RG
    type: azure/resource-group/create
    name: ${ResourceGroup}
    location: centralus

  - id: create-DB
    type: azure/cosmos/create
    resource-group: ${ResourceGroup}
    account-name: ${AccountName}
    location: westus
    databases:
      - name: FriendDatabase
        containers:
          - name: FriendContainer

            partition-key-path: /LastName

  - id: create-cosmos-cli-role
    type: azure/cosmos/create-role
    resource-group: ${ResourceGroup}
    account-name: ${AccountName}
    role-name: CLIRole
    body: "@CLIRole.json"

  - id: assign-cli-role-to-me
    type: azure/cosmos/create-assignment
    principal-id: 22395703-af19-49be-a81f-ba230562fce3
    resource-group: ${ResourceGroup}
    account-name: ${AccountName}
    role-name: "CLIRole"
